---
name: Raise PR with Changelog

on:
  push:
    branches:
      - "release-*"
    paths:
      - 'VERSION'

jobs:
  build-and-run-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto GOPATH
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
        
      - name: Build and Install Release Notes Tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "prev_tag_name=$(git show HEAD~1:VERSION)" >> $GITHUB_ENV
          echo "tag_name=$(cat VERSION)" >> $GITHUB_ENV
          echo "todays_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          ./generate-changelog.sh

      - name: Update CHANGELOG.md header
        run: |
          echo "Tag Name: ${{ env.tag_name }}"
          echo "Today's Date: ${{ env.todays_date }}"
          echo "Previous Tag Name: ${{ env.prev_tag_name }}"
          NEW_HEADER="## ${{ env.tag_name }} / ${{ env.todays_date }}"
          sed -i '1s|.*|'"$NEW_HEADER"'\n\n|' CHANGELOG.md
          cat CHANGELOG.md

      - name: Get Base SHA from Tag
        id: base_sha
        run: |
          echo "base_sha=$(git rev-list -n 1 "v${{ env.prev_tag_name }}")" >> $GITHUB_ENV
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: cut v${{ env.tag_name }}"
          title: "Cut v${{ env.tag_name }}"
          body: |
            ### Describe your PR
            This PR contains an autogenerated changelog for newer commits. 
            You can view the list of commits [here](https://github.com/${{ github.repository }}/compare/${{ env.base_sha }}...main)
            ### What type of PR is this?
            /kind NONE
            ### Changelog Entry
            ```release-note
            NONE
            ```          
          branch: changelog-branch
          signoff: true
          delete-branch: true
          labels: release-note-none
