---
name: Changelog automation

on:
  pull_request_target:
    types: [opened, edited]

permissions:
    contents: read # the config file
    pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)
    statuses: write # to generate status
    checks: write # to generate status

jobs:
  changelog-automation:
    name: Changelog automation
    runs-on: ubuntu-latest
    steps:
      - name: Release-note-none for bots
        if: ${{ github.actor == 'dependabot[bot]' }} || ${{ github.actor == 'github-actions[bot]' }} || ${{ github.actor == 'prombot' }}
        run: |
          gh pr edit "$PR_URL" --add-label "release-note-none"
          exit 0
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Remove old PR labels
        if: ${{ github.actor != 'dependabot[bot]' }} && ${{ github.actor != 'github-actions[bot]' }} && ${{ github.actor != 'prombot' }}
        uses: mondeja/remove-labels-gh-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            kind/BUGFIX
            kind/ENHANCEMENT
            kind/FEATURE
            kind/CHANGE
            release-note-none
      - name: Add label to PR
        if: ${{ github.actor != 'dependabot[bot]' }} && ${{ github.actor != 'github-actions[bot]' }} && ${{ github.actor != 'prombot' }}
        id: labeler
        uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Adjust the configuration in /.github/labeler.yml

      - name: Verify Label
        if: ${{ github.actor != 'dependabot[bot]' }} && ${{ github.actor != 'github-actions[bot]' }} && ${{ github.actor != 'prombot' }}
        id: preview_label_check
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: kind/BUGFIX,kind/ENHANCEMENT,kind/FEATURE,kind/CHANGE,release-note-none
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true
      - name: Comment on Label Check Failure
        uses: thollander/actions-comment-pull-request@v2.5.0
        if: steps.preview_label_check.outputs.label_check == 'failure' && ${{ github.actor != 'dependabot[bot]' }} && ${{ github.actor != 'github-actions[bot]' }} && ${{ github.actor != 'prombot' }}
        with:
          message: |
            PR body does not contain a valid type of change. Please refer to [CONTRIBUTING.md](https://github.com/prometheus/client_golang/blob/main/CONTRIBUTING.md#how-to-write-a-pr-description) for more information.
          comment_tag: labelfailure
          mode: recreate
      - name: Remove Label Check Failure Comment
        uses: thollander/actions-comment-pull-request@v2.5.0
        if: steps.preview_label_check.outputs.label_check == 'success' && ${{ github.actor != 'dependabot[bot]' }} && ${{ github.actor != 'github-actions[bot]' }} && ${{ github.actor != 'prombot' }}
        with:
          message: |
            PR body contains a valid type of change.
          comment_tag: labelfailure
          mode: delete
          create_if_not_exists: false
      - name: Exit on Failure
        if: steps.preview_label_check.outputs.label_check == 'failure' && ${{ github.actor != 'dependabot[bot]' }} && ${{ github.actor != 'github-actions[bot]' }} && ${{ github.actor != 'prombot' }}
        run: exit 1
