---
name: PR-auto-labeler

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, edited, synchronize]

permissions:
  contents: read # the config file
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)
  statuses: write # to generate status
  checks: write # to generate status

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch PR Body
        id: fetch_body
        run: |
          body=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r '.body')
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Check for labels in PR body
        run: |
          if [[ $(cat <<EOF 
          ${{ env.BODY }} 
          EOF) =~ /kind\ (fix|bugfix|feat|feature|enhancement|change|none|NONE|release-note-none|release-notes-none) ]] ; then
            echo "PR body contains a valid type of change"
          else
            echo "PR body does not contain a valid type of change. Please refer to CONTRIBUTING.md for more information."
            curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -X POST https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
              -d '{"body": "PR body does not contain a valid type of change. Please refer to [CONTRIBUTING.md](https://github.com/prometheus/client_golang/blob/main/CONTRIBUTING.md#how-to-fill-the-pr-template) for more information."}'
            exit 0
          fi

# Adjust the configuration in /.github/labeler.yml